In [1]:
import numpy as np 
import pandas as pd

In [2]:
delivery = pd.read_csv('deliveries.csv')
matches = pd.read_csv('matches.csv')

In [3]:
delivery.columns

Index(['id', 'inning', 'over', 'ball', 'batsman', 'non_striker', 'bowler',
       'batsman_runs', 'extra_runs', 'total_runs', 'non_boundary', 'is_wicket',
       'dismissal_kind', 'player_dismissed', 'fielder', 'extras_type',
       'batting_team', 'bowling_team'],
      dtype='object')

In [4]:
total_score_df = delivery.groupby(['id','inning']).sum()['total_runs'].reset_index()

C:\Users\gokul\AppData\Local\Temp\ipykernel_64424\1125103571.py:1: FutureWarning: The default value of numeric_only in DataFrameGroupBy.sum is deprecated. In a future version, numeric_only will default to False. Either specify numeric_only or select only columns which should be valid for the function.
  total_score_df = delivery.groupby(['id','inning']).sum()['total_runs'].reset_index()

In [5]:
total_score_df

           id  inning  total_runs
0      335982       1         222
1      335982       2          82
2      335983       1         240
3      335983       2         207
4      335984       1         129
...       ...     ...         ...
1625  1237178       2         132
1626  1237180       1         189
1627  1237180       2         172
1628  1237181       1         156
1629  1237181       2         157

[1630 rows x 3 columns]

In [6]:
total_score_df = total_score_df[total_score_df['inning'] ==1]

In [7]:
match_df = matches.merge(total_score_df[['id','total_runs']])

In [8]:
match_df['team1'].unique()

array(['Royal Challengers Bangalore', 'Kings XI Punjab',
       'Delhi Daredevils', 'Mumbai Indians', 'Kolkata Knight Riders',
       'Rajasthan Royals', 'Deccan Chargers', 'Chennai Super Kings',
       'Kochi Tuskers Kerala', 'Pune Warriors', 'Sunrisers Hyderabad',
       'Gujarat Lions', 'Rising Pune Supergiants',
       'Rising Pune Supergiant', 'Delhi Capitals'], dtype=object)

 **PRE-PROCESSING-FOR-TEAMS**

In [9]:
teams = ['Royal Challengers Bangalore',
         'Kings XI Punjab',
         'Mumbai Indians',
         'Kolkata Knight Riders',
         'Rajasthan Royals',
         'Chennai Super Kings',
         'Sunrisers Hyderabad',
         'Delhi Capitals'
       ]
match_df['team1'] = match_df['team1'].str.replace('Delhi Daredevils','Delhi Capitals')
match_df['team2'] = match_df['team2'].str.replace('Delhi Daredevils','Delhi Capitals')
match_df['toss_winner'] = match_df['toss_winner'].str.replace('Delhi Daredevils','Delhi Capitals')
match_df['winner'] = match_df['winner'].str.replace('Delhi Daredevils','Delhi Capitals')

match_df['team1'] = match_df['team1'].str.replace('Deccan Chargers','Sunrisers Hyderabad')
match_df['team2'] = match_df['team2'].str.replace('Deccan Chargers','Sunrisers Hyderabad')
match_df['toss_winner'] = match_df['toss_winner'].str.replace('Deccan Chargers','Sunrisers Hyderabad')
match_df['winner'] = match_df['winner'].str.replace('Deccan Chargers','Sunrisers Hyderabad')


match_df = match_df[match_df['team1'].isin(teams)]
match_df = match_df[match_df['team2'].isin(teams)]
match_df = match_df[match_df['toss_winner'].isin(teams)]
match_df = match_df[match_df['winner'].isin(teams)]

In [10]:
match_df['method'].unique()

array([nan, 'D/L'], dtype=object)

In [11]:
match_df['method'] = match_df['method'].fillna("0")
match_df['method']

0      0
1      0
2      0
3      0
4      0
      ..
811    0
812    0
813    0
814    0
815    0
Name: method, Length: 698, dtype: object

In [12]:
match_df['method'] = match_df['method'].apply(lambda x:x if x =="0" else "1")

match_df['method'] = match_df['method'].apply(lambda x:x if x =="0" else "1")
match_df['method'] = match_df['method'].astype('int')
match_df = match_df[match_df['method']==0]

In [13]:
match_df['method'] = match_df['method'].astype('int') 
match_df = match_df[match_df['method'] == 0]

match_df['method'].value_counts()

0    683
Name: method, dtype: int64

In [14]:
match_df

,id,city,date,player_of_match,venue,neutral_venue,team1,team2,toss_winner,toss_decision,winner,result,result_margin,eliminator,method,umpire1,umpire2,total_runs
0,335982,Bangalore,2008-04-18,BB McCullum,M Chinnaswamy Stadium,0,Royal Challengers Bangalore,Kolkata Knight Riders,Royal Challengers Bangalore,field,Kolkata Knight Riders,runs,140.0,N,0,Asad Rauf,RE Koertzen,222
1,335983,Chandigarh,2008-04-19,MEK Hussey,"Punjab Cricket Association Stadium, Mohali",0,Kings XI Punjab,Chennai Super Kings,Chennai Super Kings,bat,Chennai Super Kings,runs,33.0,N,0,MR Benson,SL Shastri,240
2,335984,Delhi,2008-04-19,MF Maharoof,Feroz Shah Kotla,0,Delhi Capitals,Rajasthan Royals,Rajasthan Royals,bat,Delhi Capitals,wickets,9.0,N,0,Aleem Dar,GA Pratapkumar,129
3,335985,Mumbai,2008-04-20,MV Boucher,Wankhede Stadium,0,Mumbai Indians,Royal Challengers Bangalore,Mumbai Indians,bat,Royal Challengers Bangalore,wickets,5.0,N,0,SJ Davis,DJ Harper,165
4,335986,Kolkata,2008-04-20,DJ Hussey,Eden Gardens,0,Kolkata Knight Riders,Sunrisers Hyderabad,Sunrisers Hyderabad,bat,Kolkata Knight Riders,wickets,5.0,N,0,BF Bowden,K Hariharan,110
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
811,1216547,Dubai,2020-09-28,AB de Villiers,Dubai International Cricket Stadium,0,Royal Challengers Bangalore,Mumbai Indians,Mumbai Indians,field,Royal Challengers Bangalore,tie,NaN,Y,0,Nitin Menon,PR Reiffel,201
812,1237177,Dubai,2020-11-05,JJ Bumrah,Dubai International Cricket Stadium,0,Mumbai Indians,Delhi Capitals,Delhi Capitals,field,Mumbai Indians,runs,57.0,N,0,CB Gaffaney,Nitin Menon,200
813,1237178,Abu Dhabi,2020-11-06,KS Williamson,Sheikh Zayed Stadium,0,Royal Challengers Bangalore,Sunrisers Hyderabad,Sunrisers Hyderabad,field,Sunrisers Hyderabad,wickets,6.0,N,0,PR Reiffel,S Ravi,131
814,1237180,Abu Dhabi,2020-11-08,MP Stoinis,Sheikh Zayed Stadium,0,Delhi Capitals,Sunrisers Hyderabad,Delhi Capitals,bat,Delhi Capitals,runs,17.0,N,0,PR Reiffel,S Ravi,189
815,1237181,Dubai,2020-11-10,TA Boult,Dubai International Cricket Stadium,0,Delhi Capitals,Mumbai Indians,Delhi Capitals,bat,Mumbai Indians,wickets,5.0,N,0,CB Gaffaney,Nitin Menon,156

**Pre Processing of toss and related**

In [15]:
# match_df['toss_decision'] = match_df['toss_decision'].apply(lambda x:0 if x == 'field' else 1)
match_df = match_df[match_df['result'] != 'tie']
match_df['result'] = match_df['result'].apply(lambda x:0 if x == 'runs' else 1)

C:\Users\gokul\AppData\Local\Temp\ipykernel_64424\2609105921.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  match_df['result'] = match_df['result'].apply(lambda x:0 if x == 'runs' else 1)

In [16]:
match_df.columns

Index(['id', 'city', 'date', 'player_of_match', 'venue', 'neutral_venue',
       'team1', 'team2', 'toss_winner', 'toss_decision', 'winner', 'result',
       'result_margin', 'eliminator', 'method', 'umpire1', 'umpire2',
       'total_runs'],
      dtype='object')

In [17]:
match_new_df = match_df[['id','venue','toss_winner','toss_decision','winner','result','total_runs']]
delivery_df = match_new_df.merge(delivery,on='id')

In [18]:
delivery_df

,id,venue,toss_winner,toss_decision,winner,result,total_runs_x,inning,over,ball,...,extra_runs,total_runs_y,non_boundary,is_wicket,dismissal_kind,player_dismissed,fielder,extras_type,batting_team,bowling_team
0,335982,M Chinnaswamy Stadium,Royal Challengers Bangalore,field,Kolkata Knight Riders,0,222,1,6,5,...,0,1,0,0,NaN,NaN,NaN,NaN,Kolkata Knight Riders,Royal Challengers Bangalore
1,335982,M Chinnaswamy Stadium,Royal Challengers Bangalore,field,Kolkata Knight Riders,0,222,1,6,6,...,0,1,0,0,NaN,NaN,NaN,NaN,Kolkata Knight Riders,Royal Challengers Bangalore
2,335982,M Chinnaswamy Stadium,Royal Challengers Bangalore,field,Kolkata Knight Riders,0,222,1,7,1,...,0,0,0,0,NaN,NaN,NaN,NaN,Kolkata Knight Riders,Royal Challengers Bangalore
3,335982,M Chinnaswamy Stadium,Royal Challengers Bangalore,field,Kolkata Knight Riders,0,222,1,7,2,...,0,1,0,0,NaN,NaN,NaN,NaN,Kolkata Knight Riders,Royal Challengers Bangalore
4,335982,M Chinnaswamy Stadium,Royal Challengers Bangalore,field,Kolkata Knight Riders,0,222,1,7,3,...,0,1,0,0,NaN,NaN,NaN,NaN,Kolkata Knight Riders,Royal Challengers Bangalore
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
160692,1237181,Dubai International Cricket Stadium,Delhi Capitals,bat,Mumbai Indians,1,156,1,12,5,...,0,0,0,0,NaN,NaN,NaN,NaN,Delhi Capitals,Mumbai Indians
160693,1237181,Dubai International Cricket Stadium,Delhi Capitals,bat,Mumbai Indians,1,156,1,12,6,...,0,1,0,0,NaN,NaN,NaN,NaN,Delhi Capitals,Mumbai Indians
160694,1237181,Dubai International Cricket Stadium,Delhi Capitals,bat,Mumbai Indians,1,156,1,13,1,...,1,1,0,0,NaN,NaN,NaN,wides,Delhi Capitals,Mumbai Indians
160695,1237181,Dubai International Cricket Stadium,Delhi Capitals,bat,Mumbai Indians,1,156,1,13,2,...,0,1,0,0,NaN,NaN,NaN,NaN,Delhi Capitals,Mumbai Indians
160696,1237181,Dubai International Cricket Stadium,Delhi Capitals,bat,Mumbai Indians,1,156,1,13,3,...,0,1,0,0,NaN,NaN,NaN,NaN,Delhi Capitals,Mumbai Indians

In [19]:
delivery_df.columns

Index(['id', 'venue', 'toss_winner', 'toss_decision', 'winner', 'result',
       'total_runs_x', 'inning', 'over', 'ball', 'batsman', 'non_striker',
       'bowler', 'batsman_runs', 'extra_runs', 'total_runs_y', 'non_boundary',
       'is_wicket', 'dismissal_kind', 'player_dismissed', 'fielder',
       'extras_type', 'batting_team', 'bowling_team'],
      dtype='object')

In [20]:
delivery_df = delivery_df[delivery_df['inning'] ==2]

In [21]:
delivery_df = delivery_df.groupby('id').apply(lambda x: x.sort_values(['over', 'ball']))

In [22]:
delivery_df.reset_index(drop=True, inplace=True)

In [23]:
delivery_df['current_score']=delivery_df.groupby('id').cumsum()['total_runs_y']

C:\Users\gokul\AppData\Local\Temp\ipykernel_64424\1613053223.py:1: FutureWarning: The default value of numeric_only in DataFrameGroupBy.cumsum is deprecated. In a future version, numeric_only will default to False. Either specify numeric_only or select only columns which should be valid for the function.
  delivery_df['current_score']=delivery_df.groupby('id').cumsum()['total_runs_y']

In [24]:
delivery_df['runs_to_win'] = delivery_df['total_runs_x'] - delivery_df['current_score']

In [25]:
delivery_df

,id,venue,toss_winner,toss_decision,winner,result,total_runs_x,inning,over,ball,...,non_boundary,is_wicket,dismissal_kind,player_dismissed,fielder,extras_type,batting_team,bowling_team,current_score,runs_to_win
0,335982,M Chinnaswamy Stadium,Royal Challengers Bangalore,field,Kolkata Knight Riders,0,222,2,0,1,...,0,0,NaN,NaN,NaN,NaN,Royal Challengers Bangalore,Kolkata Knight Riders,1,221
1,335982,M Chinnaswamy Stadium,Royal Challengers Bangalore,field,Kolkata Knight Riders,0,222,2,0,2,...,0,0,NaN,NaN,NaN,wides,Royal Challengers Bangalore,Kolkata Knight Riders,2,220
2,335982,M Chinnaswamy Stadium,Royal Challengers Bangalore,field,Kolkata Knight Riders,0,222,2,0,3,...,0,0,NaN,NaN,NaN,NaN,Royal Challengers Bangalore,Kolkata Knight Riders,2,220
3,335982,M Chinnaswamy Stadium,Royal Challengers Bangalore,field,Kolkata Knight Riders,0,222,2,0,4,...,0,0,NaN,NaN,NaN,NaN,Royal Challengers Bangalore,Kolkata Knight Riders,3,219
4,335982,M Chinnaswamy Stadium,Royal Challengers Bangalore,field,Kolkata Knight Riders,0,222,2,0,5,...,0,0,NaN,NaN,NaN,NaN,Royal Challengers Bangalore,Kolkata Knight Riders,4,218
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
77926,1237181,Dubai International Cricket Stadium,Delhi Capitals,bat,Mumbai Indians,1,156,2,17,6,...,0,0,NaN,NaN,NaN,NaN,Mumbai Indians,Delhi Capitals,154,2
77927,1237181,Dubai International Cricket Stadium,Delhi Capitals,bat,Mumbai Indians,1,156,2,18,1,...,0,0,NaN,NaN,NaN,NaN,Mumbai Indians,Delhi Capitals,155,1
77928,1237181,Dubai International Cricket Stadium,Delhi Capitals,bat,Mumbai Indians,1,156,2,18,2,...,0,0,NaN,NaN,NaN,NaN,Mumbai Indians,Delhi Capitals,156,0
77929,1237181,Dubai International Cricket Stadium,Delhi Capitals,bat,Mumbai Indians,1,156,2,18,3,...,0,1,caught,HH Pandya,AM Rahane,NaN,Mumbai Indians,Delhi Capitals,156,0
77930,1237181,Dubai International Cricket Stadium,Delhi Capitals,bat,Mumbai Indians,1,156,2,18,4,...,0,0,NaN,NaN,NaN,NaN,Mumbai Indians,Delhi Capitals,157,-1

In [26]:
delivery_df['runs_to_win'] = delivery_df['runs_to_win'] +1

In [27]:
delivery_df

,id,venue,toss_winner,toss_decision,winner,result,total_runs_x,inning,over,ball,...,non_boundary,is_wicket,dismissal_kind,player_dismissed,fielder,extras_type,batting_team,bowling_team,current_score,runs_to_win
0,335982,M Chinnaswamy Stadium,Royal Challengers Bangalore,field,Kolkata Knight Riders,0,222,2,0,1,...,0,0,NaN,NaN,NaN,NaN,Royal Challengers Bangalore,Kolkata Knight Riders,1,222
1,335982,M Chinnaswamy Stadium,Royal Challengers Bangalore,field,Kolkata Knight Riders,0,222,2,0,2,...,0,0,NaN,NaN,NaN,wides,Royal Challengers Bangalore,Kolkata Knight Riders,2,221
2,335982,M Chinnaswamy Stadium,Royal Challengers Bangalore,field,Kolkata Knight Riders,0,222,2,0,3,...,0,0,NaN,NaN,NaN,NaN,Royal Challengers Bangalore,Kolkata Knight Riders,2,221
3,335982,M Chinnaswamy Stadium,Royal Challengers Bangalore,field,Kolkata Knight Riders,0,222,2,0,4,...,0,0,NaN,NaN,NaN,NaN,Royal Challengers Bangalore,Kolkata Knight Riders,3,220
4,335982,M Chinnaswamy Stadium,Royal Challengers Bangalore,field,Kolkata Knight Riders,0,222,2,0,5,...,0,0,NaN,NaN,NaN,NaN,Royal Challengers Bangalore,Kolkata Knight Riders,4,219
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
77926,1237181,Dubai International Cricket Stadium,Delhi Capitals,bat,Mumbai Indians,1,156,2,17,6,...,0,0,NaN,NaN,NaN,NaN,Mumbai Indians,Delhi Capitals,154,3
77927,1237181,Dubai International Cricket Stadium,Delhi Capitals,bat,Mumbai Indians,1,156,2,18,1,...,0,0,NaN,NaN,NaN,NaN,Mumbai Indians,Delhi Capitals,155,2
77928,1237181,Dubai International Cricket Stadium,Delhi Capitals,bat,Mumbai Indians,1,156,2,18,2,...,0,0,NaN,NaN,NaN,NaN,Mumbai Indians,Delhi Capitals,156,1
77929,1237181,Dubai International Cricket Stadium,Delhi Capitals,bat,Mumbai Indians,1,156,2,18,3,...,0,1,caught,HH Pandya,AM Rahane,NaN,Mumbai Indians,Delhi Capitals,156,1
77930,1237181,Dubai International Cricket Stadium,Delhi Capitals,bat,Mumbai Indians,1,156,2,18,4,...,0,0,NaN,NaN,NaN,NaN,Mumbai Indians,Delhi Capitals,157,0

In [28]:
delivery_df['balls_left'] = 120 - delivery_df['over']*6 - delivery['ball']
sorted_balls_left = delivery_df.groupby('id')['balls_left'].apply(lambda x: x.sort_values(ascending=False)).reset_index(drop=True)

# Assign the sorted values back to the original DataFrame
delivery_df['balls_left'] = sorted_balls_left

In [29]:
delivery_df

,id,venue,toss_winner,toss_decision,winner,result,total_runs_x,inning,over,ball,...,is_wicket,dismissal_kind,player_dismissed,fielder,extras_type,batting_team,bowling_team,current_score,runs_to_win,balls_left
0,335982,M Chinnaswamy Stadium,Royal Challengers Bangalore,field,Kolkata Knight Riders,0,222,2,0,1,...,0,NaN,NaN,NaN,NaN,Royal Challengers Bangalore,Kolkata Knight Riders,1,222,119.0
1,335982,M Chinnaswamy Stadium,Royal Challengers Bangalore,field,Kolkata Knight Riders,0,222,2,0,2,...,0,NaN,NaN,NaN,wides,Royal Challengers Bangalore,Kolkata Knight Riders,2,221,118.0
2,335982,M Chinnaswamy Stadium,Royal Challengers Bangalore,field,Kolkata Knight Riders,0,222,2,0,3,...,0,NaN,NaN,NaN,NaN,Royal Challengers Bangalore,Kolkata Knight Riders,2,221,117.0
3,335982,M Chinnaswamy Stadium,Royal Challengers Bangalore,field,Kolkata Knight Riders,0,222,2,0,4,...,0,NaN,NaN,NaN,NaN,Royal Challengers Bangalore,Kolkata Knight Riders,3,220,116.0
4,335982,M Chinnaswamy Stadium,Royal Challengers Bangalore,field,Kolkata Knight Riders,0,222,2,0,5,...,0,NaN,NaN,NaN,NaN,Royal Challengers Bangalore,Kolkata Knight Riders,4,219,115.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
77926,1237181,Dubai International Cricket Stadium,Delhi Capitals,bat,Mumbai Indians,1,156,2,17,6,...,0,NaN,NaN,NaN,NaN,Mumbai Indians,Delhi Capitals,154,3,12.0
77927,1237181,Dubai International Cricket Stadium,Delhi Capitals,bat,Mumbai Indians,1,156,2,18,1,...,0,NaN,NaN,NaN,NaN,Mumbai Indians,Delhi Capitals,155,2,11.0
77928,1237181,Dubai International Cricket Stadium,Delhi Capitals,bat,Mumbai Indians,1,156,2,18,2,...,0,NaN,NaN,NaN,NaN,Mumbai Indians,Delhi Capitals,156,1,8.0
77929,1237181,Dubai International Cricket Stadium,Delhi Capitals,bat,Mumbai Indians,1,156,2,18,3,...,1,caught,HH Pandya,AM Rahane,NaN,Mumbai Indians,Delhi Capitals,156,1,7.0
77930,1237181,Dubai International Cricket Stadium,Delhi Capitals,bat,Mumbai Indians,1,156,2,18,4,...,0,NaN,NaN,NaN,NaN,Mumbai Indians,Delhi Capitals,157,0,6.0

In [30]:
wickets = delivery_df.groupby('id').cumsum()['is_wicket']
delivery_df['wickets_left'] = 10 - wickets

C:\Users\gokul\AppData\Local\Temp\ipykernel_64424\253533743.py:1: FutureWarning: The default value of numeric_only in DataFrameGroupBy.cumsum is deprecated. In a future version, numeric_only will default to False. Either specify numeric_only or select only columns which should be valid for the function.
  wickets = delivery_df.groupby('id').cumsum()['is_wicket']

In [31]:
delivery_df['balls_left']=delivery_df['balls_left'].astype('int')

**ADDING THE CURR AND RRR**

In [32]:
delivery_df.columns

Index(['id', 'venue', 'toss_winner', 'toss_decision', 'winner', 'result',
       'total_runs_x', 'inning', 'over', 'ball', 'batsman', 'non_striker',
       'bowler', 'batsman_runs', 'extra_runs', 'total_runs_y', 'non_boundary',
       'is_wicket', 'dismissal_kind', 'player_dismissed', 'fielder',
       'extras_type', 'batting_team', 'bowling_team', 'current_score',
       'runs_to_win', 'balls_left', 'wickets_left'],
      dtype='object')

In [33]:
delivery_df['curr'] = (delivery_df['current_score']*6/(120 -delivery_df['balls_left']))

In [34]:
delivery_df['rrr'] = ((delivery_df['runs_to_win']*6)/(delivery_df['balls_left']))

In [35]:
def result(row):
    return 1 if row['batting_team'] == row['winner'] else 0 
delivery_df['final_result'] = delivery_df.apply(result,axis=1)

In [36]:
delivery_df

,id,venue,toss_winner,toss_decision,winner,result,total_runs_x,inning,over,ball,...,extras_type,batting_team,bowling_team,current_score,runs_to_win,balls_left,wickets_left,curr,rrr,final_result
0,335982,M Chinnaswamy Stadium,Royal Challengers Bangalore,field,Kolkata Knight Riders,0,222,2,0,1,...,NaN,Royal Challengers Bangalore,Kolkata Knight Riders,1,222,119,10,6.000000,11.193277,0
1,335982,M Chinnaswamy Stadium,Royal Challengers Bangalore,field,Kolkata Knight Riders,0,222,2,0,2,...,wides,Royal Challengers Bangalore,Kolkata Knight Riders,2,221,118,10,6.000000,11.237288,0
2,335982,M Chinnaswamy Stadium,Royal Challengers Bangalore,field,Kolkata Knight Riders,0,222,2,0,3,...,NaN,Royal Challengers Bangalore,Kolkata Knight Riders,2,221,117,10,4.000000,11.333333,0
3,335982,M Chinnaswamy Stadium,Royal Challengers Bangalore,field,Kolkata Knight Riders,0,222,2,0,4,...,NaN,Royal Challengers Bangalore,Kolkata Knight Riders,3,220,116,10,4.500000,11.379310,0
4,335982,M Chinnaswamy Stadium,Royal Challengers Bangalore,field,Kolkata Knight Riders,0,222,2,0,5,...,NaN,Royal Challengers Bangalore,Kolkata Knight Riders,4,219,115,10,4.800000,11.426087,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
77926,1237181,Dubai International Cricket Stadium,Delhi Capitals,bat,Mumbai Indians,1,156,2,17,6,...,NaN,Mumbai Indians,Delhi Capitals,154,3,12,6,8.555556,1.500000,1
77927,1237181,Dubai International Cricket Stadium,Delhi Capitals,bat,Mumbai Indians,1,156,2,18,1,...,NaN,Mumbai Indians,Delhi Capitals,155,2,11,6,8.532110,1.090909,1
77928,1237181,Dubai International Cricket Stadium,Delhi Capitals,bat,Mumbai Indians,1,156,2,18,2,...,NaN,Mumbai Indians,Delhi Capitals,156,1,8,6,8.357143,0.750000,1
77929,1237181,Dubai International Cricket Stadium,Delhi Capitals,bat,Mumbai Indians,1,156,2,18,3,...,NaN,Mumbai Indians,Delhi Capitals,156,1,7,5,8.283186,0.857143,1
77930,1237181,Dubai International Cricket Stadium,Delhi Capitals,bat,Mumbai Indians,1,156,2,18,4,...,NaN,Mumbai Indians,Delhi Capitals,157,0,6,5,8.263158,0.000000,1

In [37]:
final_df = delivery_df[['batting_team','bowling_team','venue','toss_winner', 'toss_decision','runs_to_win','balls_left','wickets_left','total_runs_x','curr', 'rrr','final_result']]

In [38]:
final_df.sample(final_df.shape[0])

,batting_team,bowling_team,venue,toss_winner,toss_decision,runs_to_win,balls_left,wickets_left,total_runs_x,curr,rrr,final_result
62982,Chennai Super Kings,Sunrisers Hyderabad,Maharashtra Cricket Association Stadium,Chennai Super Kings,field,143,95,10,179,8.880000,9.031579,1
3524,Kings XI Punjab,Chennai Super Kings,"MA Chidambaram Stadium, Chepauk",Kings XI Punjab,field,123,69,8,181,6.941176,10.695652,0
17958,Delhi Daredevils,Mumbai Indians,Brabourne Stadium,Mumbai Indians,bat,64,19,4,183,7.128713,20.210526,0
71142,Chennai Super Kings,Delhi Capitals,Dr. Y.S. Rajasekhara Reddy ACA-VDCA Cricket St...,Chennai Super Kings,field,147,117,10,147,2.000000,7.538462,1
36518,Rajasthan Royals,Chennai Super Kings,Sawai Mansingh Stadium,Rajasthan Royals,field,96,62,6,141,4.758621,9.290323,1
...,...,...,...,...,...,...,...,...,...,...,...,...
28895,Kolkata Knight Riders,Delhi Daredevils,Feroz Shah Kotla,Delhi Capitals,bat,133,103,10,153,7.411765,7.747573,1
68575,Delhi Capitals,Mumbai Indians,Feroz Shah Kotla,Mumbai Indians,bat,60,13,2,168,6.112150,27.692308,0
76825,Rajasthan Royals,Mumbai Indians,Sheikh Zayed Stadium,Mumbai Indians,bat,93,55,8,195,9.507692,10.145455,1
25533,Delhi Daredevils,Chennai Super Kings,Feroz Shah Kotla,Delhi Capitals,field,27,58,8,110,8.129032,2.793103,0
27176,Kolkata Knight Riders,Deccan Chargers,Barabati Stadium,Kolkata Knight Riders,field,19,17,5,126,6.291262,6.705882,1

In [39]:
final_df = final_df[final_df['balls_left'] != 0] 
final_df.dropna(inplace= True)

**Encoding data**

In [40]:
from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import ColumnTransformer

In [41]:
final_df.columns

Index(['batting_team', 'bowling_team', 'venue', 'toss_winner', 'toss_decision',
       'runs_to_win', 'balls_left', 'wickets_left', 'total_runs_x', 'curr',
       'rrr', 'final_result'],
      dtype='object')

In [42]:



trf1 = ColumnTransformer(
    [
        ('trf1', 'passthrough', [ 'runs_to_win', 'balls_left', 'wickets_left', 'total_runs_x', 'curr',
       'rrr']),  # Columns not to be encoded
        ('trf2', OneHotEncoder(sparse=False, drop='first'), ['batting_team', 'bowling_team', 'venue', 'toss_winner','toss_decision'])
    ]
)

In [43]:
from sklearn.linear_model import LogisticRegression
from sklearn.pipeline import Pipeline

In [44]:
pipe = Pipeline(steps= [
    ('step1',trf1),
    ('step2',LogisticRegression(solver = 'liblinear'))
]
               )

In [45]:
X = final_df.iloc[:,:-1]
y = final_df.iloc[:,-1]
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size = 0.2,random_state = 6)

In [46]:
pipe.fit(X_train,y_train)

C:\Users\gokul\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\preprocessing\_encoders.py:972: FutureWarning: `sparse` was renamed to `sparse_output` in version 1.2 and will be removed in 1.4. `sparse_output` is ignored unless you leave `sparse` to its default value.
  warnings.warn(

Pipeline(steps=[('step1',
                 ColumnTransformer(transformers=[('trf1', 'passthrough',
                                                  ['runs_to_win', 'balls_left',
                                                   'wickets_left',
                                                   'total_runs_x', 'curr',
                                                   'rrr']),
                                                 ('trf2',
                                                  OneHotEncoder(drop='first',
                                                                sparse=False),
                                                  ['batting_team',
                                                   'bowling_team', 'venue',
                                                   'toss_winner',
                                                   'toss_decision'])])),
                ('step2', LogisticRegression(solver='liblinear'))])

In [47]:
y_pred = pipe.predict(X_test)
from sklearn.metrics import accuracy_score
accuracy_score(y_test,y_pred)

0.8484926565318217

In [48]:
teams

['Royal Challengers Bangalore',
 'Kings XI Punjab',
 'Mumbai Indians',
 'Kolkata Knight Riders',
 'Rajasthan Royals',
 'Chennai Super Kings',
 'Sunrisers Hyderabad',
 'Delhi Capitals']

In [49]:
delivery_df['venue'].unique()

array(['M Chinnaswamy Stadium',
       'Punjab Cricket Association Stadium, Mohali', 'Feroz Shah Kotla',
       'Wankhede Stadium', 'Eden Gardens', 'Sawai Mansingh Stadium',
       'Rajiv Gandhi International Stadium, Uppal',
       'MA Chidambaram Stadium, Chepauk', 'Dr DY Patil Sports Academy',
       'Newlands', "St George's Park", 'Kingsmead', 'SuperSport Park',
       'Buffalo Park', 'New Wanderers Stadium', 'De Beers Diamond Oval',
       'OUTsurance Oval', 'Brabourne Stadium',
       'Sardar Patel Stadium, Motera', 'Barabati Stadium',
       'Vidarbha Cricket Association Stadium, Jamtha',
       'Himachal Pradesh Cricket Association Stadium',
       'Dr. Y.S. Rajasekhara Reddy ACA-VDCA Cricket Stadium',
       'Subrata Roy Sahara Stadium',
       'Shaheed Veer Narayan Singh International Stadium',
       'JSCA International Stadium Complex', 'Sheikh Zayed Stadium',
       'Sharjah Cricket Stadium', 'Dubai International Cricket Stadium',
       'Maharashtra Cricket Association Stadium',
       'Punjab Cricket Association IS Bindra Stadium, Mohali',
       'M.Chinnaswamy Stadium', 'Holkar Cricket Stadium'], dtype=object)

In [50]:
import pickle 
pickle.dump(pipe,open('pipe.pkl','wb'))

In [51]:
final_df['toss_decision'].unique()

array(['field', 'bat'], dtype=object)

In [52]:
final_df.columns

Index(['batting_team', 'bowling_team', 'venue', 'toss_winner', 'toss_decision',
       'runs_to_win', 'balls_left', 'wickets_left', 'total_runs_x', 'curr',
       'rrr', 'final_result'],
      dtype='object')